### PR TITLE
Show 'text' instead of 'value' on focusout outside of dropdown

### PR DESCRIPTION
**Pull request by kristina-kurshakova-sociomantic**
How To Reproduce: 
 - Have items with unequeal `value` and `text`
 - Open dropdown 
 - Click outside of dropdown
 - Instead of previously showed `value` will `text` be shown

### CODE REVIEW

**Comment by mousemke** [comment]
without a branch for it (or other specific need to not up the version) this would be pushed to 0.6.3 on npm.  can you add a readme update of the change and run the node script to update things to 0.6.3? Of course, tests would be awesome, but yeah, the rest of the repo tests are also fairly lacking

**Comment by kristina-kurshakova-sociomantic** [comment]
@mousemke added test and description to v 0.6.3.

**Comment by kristina-kurshakova-sociomantic** [comment]
@mousemke done

**Comment by mousemke** [comment]
merged but into the 0.6.3 branch over here. https://github.com/sociomantic-tsunami/flounder/pull/62

**Pull request closed without merging**
